Repository NewSainTurtle/ShadowMate, pull requests merged in 2023-11, with the labels that each got.

#280 [BE] 캘린더 접근 권한 확인 에러 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
Labels: backend, fix

#277 [FE] 일별 플래너 API 연결
  FE/package-lock.json
  FE/package.json
  FE/src/api/firebaseConfig.ts
  FE/src/components/common/Dday/index.tsx
  FE/src/components/planner/day/CustomCursor.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/Ment.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoItemChoice.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/pages/commonPage.tsx
  FE/src/store/planner/daySlice.ts
  FE/src/store/planner/weekSlice.ts
  FE/src/styles/planner/day.module.scss
  FE/src/util/data/DayTodos.ts
Labels: frontend, feature, setting

#284 [FE] 카테고리 ID 에러 수정
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
Labels: frontend, feature, fix

#285 [FE] 마이페이지 다이어리 공개 여부 설정 API 연결
  FE/src/components/mypage/details/diary/Diary.tsx
  FE/src/components/planner/month/Month.tsx
  FE/src/store/planner/monthSlice.ts
Labels: frontend, feature

#287 [BE] 내 정보 설정 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UpdateUserRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, feature, test

#282 [BE] 공개된 플래너 닉네임 검색 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/social/constant/SocialConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/controller/SocialController.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/dto/SearchNicknamePublicDailyPlannerRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/dto/SearchPublicDailyPlannerResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/dto/SearchSocialResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialService.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java
Labels: backend, feature, test

#289 [BE] 비밀번호 수정 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UpdatePasswordRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/exception/UserErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, feature, test

#293 [FE] 주별 플래너 API 연결
  FE/src/components/common/CategorySelector/index.tsx
  FE/src/components/planner/week/Week.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/components/planner/week/list/WeekItemInput.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/store/planner/weekSlice.ts
Labels: frontend, feature

#296 [BE] 팔로우 신청 응답 API 수정
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
Labels: backend, fix

#297 [BE] 팔로우 신청 응답 API 수정
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
Labels: backend, fix

#298 [FE] 마이페이지 친구 API 연결
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/mypage/details/friend/MyFriend.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
  FE/src/components/planner/day/CustomCursor.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/hooks/configStore.ts
  FE/src/pages/commonPage.tsx
  FE/src/store/friendSlice.ts
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/EventControlModule.tsx
  FE/src/util/data/DayTodos.ts
  FE/src/util/data/FriendData.ts
  FE/src/util/data/SocialData.ts
  FE/src/util/friend.interface.ts
Labels: frontend, feature

#299 [BE] Jacoco 설정
  BE/build.gradle
  BE/lombok.config
  BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/SendEmailAuthenticationCodeRequest.java
Labels: backend, setting

#300 [FE] 내 정보 설정 API 연결 및 기본 내 프로필 적용
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/components/auth/login/Login.tsx
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/MyPageTab.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
  FE/src/components/mypage/details/myInfo/CancleMembership.tsx
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/mypage/details/myInfo/MyPassword.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/components/planner/week/Week.tsx
  FE/src/components/social/CardItem.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/commonPage.tsx
  FE/src/store/authSlice.ts
  FE/src/store/friendSlice.ts
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/data/DayTodos.ts
  FE/src/util/data/SocialData.ts
  FE/src/util/regex.ts
Labels: frontend, design, feature

#291 [BE] 공유 플래너 삭제 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/social/constant/SocialConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/controller/SocialController.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/exception/SocialErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialService.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java
Labels: backend, feature, test

#302 [BE] 소나큐브 코드 악취 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetails.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthControlloerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java
Labels: backend, fix, test, refactor

#301 [BE] 닉네임 중복검사 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, feature, test

#306 [BE] 소나큐브 코드 악취 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/SecurityConfig.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtExceptionHandler.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/ShadowmateApplicationTests.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, fix, refactor

#304 [FE] 공통 모달 컴포넌트 수정 및 alert, 로딩 컴포넌트 생성
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/common/Alert/index.tsx
  FE/src/components/common/Loading/index.tsx
  FE/src/components/common/Modal/index.tsx
  FE/src/components/mypage/details/diary/Diary.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/pages/commonPage.tsx
  FE/src/styles/common/Alert.module.scss
  FE/src/styles/common/Loading.module.scss
  FE/src/styles/common/Modal.module.scss
  FE/src/styles/mypage/MyPage.module.scss
Labels: frontend, design, feature

#308 [FE] 공통 모달 컴포넌트 충돌 해결
  FE/src/api/Api.ts
  FE/src/components/mypage/details/myInfo/CancelMembership.tsx
  FE/src/pages/MyPage.tsx
Labels: frontend, fix

#310 [FE] 프론트엔드 빌드 에러 해결
  FE/config/webpack.prod.js
Labels: frontend, fix

#312 [FE] 카테고리, 디데이 slice 분리, 모달 slice 생성
  FE/src/components/common/CategorySelector/index.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/mypage/item/CategoryColorItem.tsx
  FE/src/components/mypage/item/MyPageCategoryItem.tsx
  FE/src/components/mypage/item/MyPageDdayItem.tsx
  FE/src/components/mypage/list/CategoryList.tsx
  FE/src/components/mypage/list/DdayList.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/hooks/configStore.ts
  FE/src/pages/MyPage.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/store/modalSlice.ts
  FE/src/store/mypage/categorySlice.ts
  FE/src/store/mypage/ddaySlice.ts
  FE/src/store/mypageSlice.ts
  FE/src/util/data/CategoryData.ts
  FE/src/util/data/DayTodos.ts
  FE/src/util/data/DdayData.ts
  FE/src/util/planner.interface.ts
Labels: frontend, refactor

#315 [BE] 닉네임 중복검증 API Redis 수정
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/exception/UserErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, fix, test, refactor

#320 [BE] 팔로잉 조회 API 수정
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowingResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
Labels: backend, refactor

#322 [BE] 일일 플래너 조회 시 소셜 공유 여부 확인하기
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/SearchDailyPlannerResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java
Labels: backend, feature, test, refactor

#323 [BE] 회원 검색 빈값 수정
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, fix, refactor

#326 [BE] 팔로워 조회 API 응답 수정
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowerResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, fix, test, refactor

#325 [FE] 토큰 만료 시 로그인 페이지로 리다이렉트, 로그인 및 회원탈퇴 시 redux 초기화
  FE/src/App.tsx
  FE/src/api/JsonAxios.ts
  FE/src/components/common/Modal/TokenExpiration.tsx
  FE/src/components/common/Modal/index.tsx
  FE/src/components/mypage/details/myInfo/CancelMembership.tsx
  FE/src/store/authSlice.ts
  FE/src/store/modalSlice.ts
  FE/src/styles/common/Modal.module.scss
Labels: frontend, feature

#316 [FE] 일별 플래너 소셜 공유 API 연결 및 일부 기능 수정
  FE/package-lock.json
  FE/package.json
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/Ment.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/pages/commonPage.tsx
  FE/src/store/planner/daySlice.ts
Labels: frontend, design, feature

#330 [BE] 충돌 수정
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
Labels: backend, fix

#327 [FE] 캘린더 팔로잉 목록 API 연결
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/styles/planner/Month.module.scss
Labels: frontend, feature

#332 [FE] 토큰 만료 모달 에러 수정
  FE/src/api/JsonAxios.ts
Labels: frontend, fix

#338 [BE] 일일플래너 소셜 공유시 플래너 공개범위 확인
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/FollowRequestRepositoryTest.java
Labels: backend, feature, fix, test

#340 [BE] 닉네임 중복검사 API 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java
Labels: backend, test, refactor

#342 [BE] 성공 상태코드 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
Labels: backend, refactor

#343 [BE] 성공 상태 코드 수정
  BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/controller/SocialController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthControlloerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
Labels: backend, fix, refactor

#333 [FE] 소셜공유 API 연결
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/components/planner/day/Header.tsx
  FE/src/components/social/CardItem.tsx
  FE/src/components/social/CardList.tsx
  FE/src/components/social/SocialHeader.tsx
  FE/src/pages/SocialPage.tsx
  FE/src/store/friendSlice.ts
  FE/src/styles/social/Social.module.scss
Labels: frontend, feature

#347 [BE] 공개된 플래너 최신순 정렬 수정
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
Labels: backend, refactor

#357 [BE] 비밀번호 변경 API 수정
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
Labels: backend, fix, refactor

#354 [FE] 로그아웃 및 사용자 테마 저장
  FE/src/App.tsx
  FE/src/components/auth/AuthHeader.tsx
  FE/src/components/common/Header/Toggle.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/details/myInfo/CancelMembership.tsx
  FE/src/store/authSlice.ts
  FE/src/styles/auth/Landing.module.scss
  FE/src/styles/common/Profile.module.scss
Labels: frontend, design, feature

#358 [FE] 내 프로필 / 친구 프로필 이동 기능 구현
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/common/Header/Menu.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/planner/month/Month.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/components/planner/week/Week.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/friendSlice.ts
Labels: frontend, feature

#361 [FE] 구글 로그인 시 사용자 정보 저장 및 비밀번호 변경 탭 삭제
  FE/src/App.tsx
  FE/src/components/auth/login/Login.tsx
  FE/src/components/mypage/MyPageTab.tsx
  FE/src/store/authSlice.ts
Labels: frontend, feature, fix

#366 [FE] 구글 로그인 에러 수정
  FE/src/components/auth/login/Login.tsx
Labels: frontend, fix

#356 [FE] 페이지 UI 페인팅 개선
  FE/src/components/auth/AuthHeader.tsx
  FE/src/components/mypage/details/friend/MyFriend.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
  FE/src/components/social/CardList.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/styles/common/Input.module.scss
Labels: frontend, design, feature

#364 [FE] 다른 사용자가 보는 일별 플래너
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/week/Week.tsx
  FE/src/components/social/CardItem.tsx
  FE/src/components/social/CardList.tsx
Labels: frontend, design, feature

#368 [FE] 프론트 빌드 설정 변경
  FE/package.json
Labels: frontend, fix

#350 [FE] 로딩 및 알림(Alert) 추가
  FE/src/App.tsx
  FE/src/api/JsonAxios.ts
  FE/src/components/common/Alert/index.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/components/planner/week/Week.tsx
  FE/src/hooks/configStore.ts
  FE/src/pages/Planner/DayPage.tsx
  FE/src/pages/commonPage.tsx
  FE/src/store/alertSlice.ts
  FE/src/styles/common/Loading.module.scss
Labels: frontend, feature

#373 [FE] 프론트 빌드 설정 변경
  FE/Dockerfile
Labels: frontend, refactor

#375 [FE] 프론트 빌드 설정 변경
  FE/package.json
Labels: frontend, refactor

#376 [FE] 프론트 빌드 설정 변경
  FE/Dockerfile
Labels: frontend, refactor

#351 [FE] 일별 플래너 친구 좋아요 추가/취소 API 연결
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/Ment.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/planner/daySlice.ts
  FE/src/styles/planner/day.module.scss
Labels: frontend, feature

#372 [FE] 404 페이지 생성 및 연결
  FE/src/App.tsx
  FE/src/assets/Imgs/logo_dark.svg
  FE/src/assets/Imgs/logo_light.svg
  FE/src/pages/NotFoundPage.tsx
  FE/src/styles/NotFound.module.scss
Labels: frontend, design, feature

#369 [FE] 친구 주별 플래너 수정 막기
  FE/src/components/planner/week/Week.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/components/planner/week/todo/WeekTodo.tsx
  FE/src/styles/common/Profile.module.scss
  FE/src/styles/planner/Week.module.scss
Labels: frontend, design, feature

#379 [FE] 소셜 페이지 이미지 로딩
  FE/src/components/social/CardItem.tsx
  FE/src/components/social/CardList.tsx
  FE/src/pages/SocialPage.tsx
  FE/src/styles/social/Social.module.scss
Labels: frontend, design, feature

#378 [FE] redux-persist 암호화 라이브러리 설치 및 설정 추가
  FE/package.json
  FE/src/hooks/configStore.ts
Labels: frontend, feature

#385 [FE] 일별 플래너 일부 수정
  FE/src/components/common/Dday/index.tsx
  FE/src/components/common/Header/Menu.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/todo/TodoItemChoice.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/components/social/CardItem.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/planner/daySlice.ts
  FE/src/styles/common/Profile.module.scss
  FE/src/styles/planner/Week.module.scss
  FE/src/styles/planner/day.module.scss
Labels: frontend, design, feature, refactor

#392 [BE] 캘린더 조회 API에 월별 통계 추가
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/CalendarDayTotalResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/SearchCalendarResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
Labels: backend, feature, test

#383 [BE] 방명록 추가 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddVisitorBookRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/AddVisitorBookResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/VisitorBook.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/VisitorBookRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/MonthlyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/VisitorBookRepositoryTest.java
Labels: backend, feature, test

#394 [BE] 방명록 삭제 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/RemoveVisitorBookRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/VisitorBookRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/MonthlyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/VisitorBookRepositoryTest.java
Labels: backend, feature, test

#393 [BE] 소개글 작성 API 추가
  BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UpdateIntroductionRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, test

#396 [FE] auth페이지 헤더 변경
  FE/src/components/auth/AuthHeader.tsx
Labels: frontend, design, refactor

#387 [FE] 회원 가입 에러 로직 변경
  FE/src/components/auth/signup/Signup.tsx
  FE/src/components/common/Input/index.tsx
  FE/src/styles/auth/Signup.module.scss
  FE/src/util/regex.ts
Labels: frontend, design, refactor

#402 [FE] 캘린더 컴포넌트 생성 및 배치
  FE/src/App.scss
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/common/FriendProfileIcon/index.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/planner/month/Month.tsx
  FE/src/components/planner/month/MonthDetail.tsx
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
  FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx
  FE/src/components/planner/month/MonthDetailInfo/Statistics.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/components/planner/month/MonthIconBox.tsx
  FE/src/styles/common/Profile.module.scss
  FE/src/styles/planner/Month.module.scss
  FE/src/util/data/GuestBookData.ts
Labels: frontend, design, feature

#397 [BE] 방명록 조회 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/SearchVisitorBookResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/VisitorBookResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/VisitorBookRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/MonthlyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/VisitorBookRepositoryTest.java
Labels: backend, feature, test

#400 [BE] 캘린더 조회 API에 좋아요 월별 카운트 기능 추가
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/CalendarDayTotalResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/SearchCalendarResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerLikeRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java
Labels: backend, feature, test

#411 [BE] 구글로그인 주소 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/SecurityConfig.java
Labels: backend, refactor

#413 [BE] 팔로우 팔로잉 카운트 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/CountFollowResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
Labels: backend, feature, test

#405 [FE] 팔로우 친구 신청 수정
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
Labels: frontend, feature, refactor

#415 [BE] API업데이트 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
Labels: backend, refactor

#416 [BE] 플래너 설정 부분 데이터 업데이트 코드 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/common/entity/CommonEntity.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Category.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
Labels: backend, refactor

#418 [BE] 코드 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
Labels: backend, refactor

#420 [BE] 일일 플래너 부분 데이터 업데이트 코드 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/entity/Social.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
Labels: backend, refactor

#423 [BE] 비밀번호 Test코드 수정
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
Labels: backend, test, refactor

#421 [BE] 탈퇴회원 로그인 코드 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetailsService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
Labels: backend, refactor

#425 [BE] 주간 플래너 부분 데이터 업데이트 코드 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/WeeklyTodo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
Labels: backend, refactor

#428 [BE] 플래너 공개 여부 설정 코드 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
Labels: backend, refactor

#426 [BE] 유저 탈퇴 API 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, test, refactor

#430 [BE] PlannerAccessScope 타입 변경
  BE/src/main/java/com/newsainturtle/shadowmate/user/dto/ProfileResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
Labels: backend, refactor

#406 [FE] 주별 플래너 작성 시 이전 내용 없어지는 에러 수정
  FE/src/components/planner/week/list/WeekList.tsx
Labels: frontend, fix

#427 [FE] 기본 프로필 Avatar 수정
  FE/src/components/common/Avatar/index.tsx
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/common/FriendProfileIcon/index.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
  FE/src/components/social/CardItem.tsx
  FE/src/styles/common/Avatar.module.scss
Labels: frontend, design, feature

#431 [FE] 캘린더에서 주별 플래너로 이동하는 기능 구현
  FE/src/components/planner/month/Month.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/components/planner/week/Week.tsx
  FE/src/store/planner/weekSlice.ts
  FE/src/styles/planner/Month.module.scss
  FE/src/util/getThisWeek.ts
Labels: frontend, feature, refactor

#432 [FE] 다이어리 공개 여부 API 수정 반영
  FE/src/components/planner/month/Month.tsx
Labels: frontend, fix

#436 [FE] 캘린더 비공개 에러 수정
  FE/src/components/planner/month/Month.tsx
Labels: frontend, fix

#437 [BE] 방명록 에러 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/VisitorBookRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/MonthlyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/VisitorBookRepositoryTest.java
Labels: backend, fix

#444 [BE] 소개글 조회 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/dto/SearchIntroductionResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, feature, test

#449 [BE] 팔로우 팔로잉 개수 조회 유저검증 API 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
Labels: backend, test, refactor

#439 [FE] 주별 플래너 헤더 수정 및 일별 이동 기능 구현
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/week/Week.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/styles/planner/Week.module.scss
Labels: frontend, design, feature

#442 [FE] 마이페이지 에러 및 CSS 수정
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/mypage/details/diary/Diary.tsx
  FE/src/store/authSlice.ts
  FE/src/store/mypage/categorySlice.ts
  FE/src/store/mypage/ddaySlice.ts
  FE/src/store/planner/monthSlice.ts
  FE/src/styles/mypage/MyPage.module.scss
Labels: frontend, design, fix

#450 [FE] 일별 플래너 에러 수정 & 소셜공유
  FE/src/components/planner/day/Ment.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/styles/planner/day.module.scss
Labels: frontend, design, feature

#451 [FE] 주별 플래너 에러 수정
  FE/src/components/planner/week/todo/WeekTodo.tsx
  FE/src/components/planner/week/todo/WeekTodoInput.tsx
  FE/src/components/planner/week/todo/WeekTodoItem.tsx
  FE/src/styles/planner/Week.module.scss
Labels: frontend, fix

#453 [FE] 비밀번호 변경 API 수정/상태메세지 모든 문자 허용
  FE/src/api/Api.ts
  FE/src/util/regex.ts
Labels: frontend, fix, refactor

#454 [FE] 공통 컴포넌트 Avatar property 에러 수정
  FE/src/components/common/Avatar/index.tsx
Labels: frontend, fix

#458 [FE] 소셜 닉네임 검색후 정렬 추가
  FE/src/components/social/SocialHeader.tsx
Labels: frontend, feature, fix

#461 [FE] 토큰 만료 에러 수정
  FE/src/api/JsonAxios.ts
Labels: frontend, fix, refactor

#462 [FE] 이미지 확장자 제한 및 이미지 리사이징 업로드
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/planner/day/Ment.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/util/resizeImage.ts
Labels: frontend, feature, refactor

#470 [BE] 회원탈퇴시 팔로우삭제 API 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, test, refactor

#472 [BE] 최신순 정렬 API 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
Labels: backend, refactor

#467 [FE] 디데이 삭제 에러 수정
  FE/src/components/mypage/MyPageFrame.tsx
Labels: feature, fix

#474 [FE] 랜딩 배경 이미지 변경
  FE/src/assets/Imgs/landing_background.svg
Labels: frontend, design, refactor

#456 [FE] 캘린더 API 연결
  FE/src/App.tsx
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/MyPageTab.tsx
  FE/src/components/planner/month/Month.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
  FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx
  FE/src/components/planner/month/MonthDetailInfo/Statistics.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/components/planner/month/MonthIconBox.tsx
  FE/src/components/social/CardList.tsx
  FE/src/pages/MyPage.tsx
  FE/src/store/planner/monthSlice.ts
  FE/src/styles/planner/Month.module.scss
  FE/src/util/data/GuestBookData.ts
  FE/src/util/planner.interface.ts
Labels: frontend, feature

#469 [FE] 캘린더 공개 여부 조회 리팩토링
  FE/src/components/planner/month/Month.tsx
Labels: frontend, refactor

#475 [FE] 로그인 자동 로그인, 비밀번호 찾기 버튼 삭제
  FE/src/components/auth/login/Login.tsx
Labels: frontend, feature

#483 [FE] 공통 삭제 모달 생성 및 연결
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/common/Modal/DeleteModal.tsx
  FE/src/components/common/Modal/index.tsx
  FE/src/components/mypage/MyPageDetail.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/components/planner/week/todo/WeekTodoItem.tsx
  FE/src/components/social/CardItem.tsx
  FE/src/components/social/CardList.tsx
  FE/src/styles/common/Modal.module.scss
Labels: frontend, feature

#482 [FE] 팔로우 연속 삭제/플래너에서 친구 추가 에러 해결
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
Labels: frontend, feature, fix

#486 [FE] 주별 플래너 일정 생성 시 자동 저장 기능 추가
  FE/src/components/planner/week/list/WeekItemInput.tsx
  FE/src/components/planner/week/todo/WeekTodoInput.tsx
Labels: frontend, feature

#488 [FE] 카테고리 선택창에 카테고리 추가 버튼 생성 및 페이지 연결
  FE/src/App.tsx
  FE/src/components/common/CategorySelector/index.tsx
  FE/src/components/mypage/MyPageTab.tsx
  FE/src/styles/mypage/MyPage.module.scss
Labels: frontend, design, feature

#490 [FE] 캘린더 소개글 수정 시 글자색 변경 및 개행 반영
  FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx
  FE/src/components/planner/month/MonthIconBox.tsx
  FE/src/styles/planner/Month.module.scss
Labels: frontend, design, feature
