Repository NewSainTurtle/ShadowMate, pull requests merged in 2023-10, with the labels that each got.

#91 [FE] 소셜 컴포넌트 생성 및 배치
  FE/config/webpack.config.js
  FE/config/webpack.dev.js
  FE/package-lock.json
  FE/package.json
  FE/src/api/Api.ts
  FE/src/components/social/CardItem.tsx
  FE/src/components/social/CardList.tsx
  FE/src/components/social/Social.tsx
  FE/src/components/social/SocialHeader.tsx
  FE/src/pages/SocialPage.tsx
  FE/src/styles/social/Social.module.scss
  FE/src/util/data/SocialData.ts
Labels: frontend, design, feature, setting

#104 [BE] 오늘의 회고 편집 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateRetrospectionRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
Labels: backend, feature, test

#107 [BE] 코드 오류 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
Labels: backend, fix

#108 [BE] 오늘의 회고 사진 업로드 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateRetrospectionImageRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
Labels: backend, feature, test

#110 [BE] 일일 플래너 할일 수정 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateDailyTodoRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/enums/TodoStatus.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
Labels: backend, feature, test, refactor

#114 [BE] 카테고리 삭제 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/RemoveCategoryRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/CategoryRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
Labels: backend, feature, test

#115 [BE] 주차별 할일 등록 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddWeeklyTodoRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddWeeklyTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Weekly.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/WeeklyTodo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyTodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
Labels: backend, feature, test

#117 [BE] 팔로잉 조회 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/common/GlobalExceptionHandler.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowingResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/Follow.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowException.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
Labels: backend, feature, test, refactor

#118 [BE] 타임 테이블 등록 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddTimeTableRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddTimeTableResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/TimeTable.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TimeTableRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
Labels: backend, feature, test

#112 [FE] 마이페이지 카테고리 생성, 수정 및 삭제 기능 구현
  FE/package-lock.json
  FE/src/components/common/Input/index.tsx
  FE/src/components/mypage/MyPageDetail.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/MyPageList.tsx
  FE/src/components/mypage/MyPageTab.tsx
  FE/src/components/mypage/details/MyPageCategory.tsx
  FE/src/components/mypage/details/MyPageDday.tsx
  FE/src/components/mypage/details/MyPageDiary.tsx
  FE/src/components/mypage/item/CategoryColorItem.tsx
  FE/src/components/mypage/item/CategoryColorList.tsx
  FE/src/components/mypage/item/MyPageCategoryItem.tsx
  FE/src/components/mypage/item/MyPageDdayItem.tsx
  FE/src/pages/MyPage.tsx
  FE/src/styles/common/Profile.module.scss
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/data/CategoryData.ts
  FE/src/util/data/DdayData.ts
  FE/src/util/planner.interface.ts
Labels: frontend, feature

#121 [BE] 주차별 할일 내용 수정 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateWeeklyTodoContentRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyTodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
Labels: backend, feature, test

#126 [BE] 타임 테이블 삭제 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/RemoveTimeTableRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TimeTableRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
Labels: backend, feature, test

#124 [BE] 팔로잉 조회 API 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowingResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
Labels: backend, test, refactor

#132 [BE] 주차별 할일 상태 수정 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateWeeklyTodoStatusRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
Labels: backend, feature, test

#128 [FE] 일별 플래너 일부 기능 추가 및 수정
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/TodoItem.tsx
  FE/src/components/planner/day/TodoList.tsx
  FE/src/components/social/CardItem.tsx
  FE/src/components/social/CardList.tsx
  FE/src/components/social/SocialHeader.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/pages/SocialPage.tsx
  FE/src/styles/planner/day.module.scss
  FE/src/util/data/DayTodos.ts
  FE/src/util/planner.interface.ts
Labels: frontend, design, feature, refactor

#129 [FE] 마이페이지 내 정보 수정 컴포넌트 생성 및 배치
  FE/package-lock.json
  FE/src/components/mypage/details/MyPageInfo.tsx
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/data/MyInfoData.ts
Labels: frontend, design, feature

#138 [BE] 할일과 타임테이블 엔티티 연관관계 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddTimeTableResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/RemoveTimeTableRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/TimeTable.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TimeTableRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
Labels: backend, feature, test

#139 [BE] 좋아요 로직 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddDailyLikeRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/RemoveDailyLikeRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/UserRepositoryTest.java
Labels: backend, feature, test

#142 [BE] 주차별 할일 삭제 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/RemoveWeeklyTodoRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyTodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
Labels: backend, feature, test

#144 [FE] 마이페이지 디데이 생성, 수정 및 삭제 기능 구현
  FE/package-lock.json
  FE/package.json
  FE/src/components/common/Input/index.tsx
  FE/src/components/mypage/MyPageDetail.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/MyPageList.tsx
  FE/src/components/mypage/details/MyPageDday.tsx
  FE/src/components/mypage/item/MyPageCategoryItem.tsx
  FE/src/components/mypage/item/MyPageDdayItem.tsx
  FE/src/styles/common/Input.module.scss
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/data/DdayData.ts
  FE/src/util/getThisWeek.ts
Labels: frontend, feature, refactor

#150 [BE] 회원검색 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/follow/enums/FollowStatus.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UserResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/exception/UserErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, feature, test

#151 [BE] 주간플래너 조회 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/DailyPlannerTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/DailyPlannerTodoTimeTableResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/SearchDailyPlannerResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/SearchWeeklyPlannerResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/WeeklyPlannerDailyResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/WeeklyPlannerDailyTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/WeeklyPlannerTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyTodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
Labels: backend, feature, test

#155 [BE] 팔로워 삭제 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/DeleteFollowerRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
Labels: backend, feature, test

#158 [BE] 팔로우신청 취소 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/DeleteFollowRequestRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java
Labels: backend, feature, test

#160 [BE] 캘린더 조회 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/CalendarDayResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/SearchCalendarResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
Labels: backend, feature, test

#161 [FE] 마이페이지 다이어리 설정 컴포넌트 수정
  FE/src/components/common/Modal/index.tsx
  FE/src/components/common/RadioButton/index.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/MyPageTab.tsx
  FE/src/components/mypage/details/MyPageDiary.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/mypage/details/diary/Diary.tsx
  FE/src/components/mypage/details/friend/Follower.tsx
  FE/src/components/mypage/details/friend/Following.tsx
  FE/src/components/mypage/details/friend/MyPageFriend.tsx
  FE/src/components/mypage/details/friend/Search.tsx
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/pages/MyPage.tsx
  FE/src/styles/mypage/MyPage.module.scss
Labels: frontend, feature, refactor

#162 [FE] 마이페이지 친구 컴포넌트 생성 및 배치
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/mypage/details/friend/MyFriend.tsx
  FE/src/components/mypage/details/friend/MyPageFriend.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/commonPage.tsx
  FE/src/styles/common/Profile.module.scss
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/data/FriendData.ts
  FE/src/util/friend.interface.ts
Labels: frontend, design, feature

#165 [FE] 마이페이지 탭 input 태그 에러 수정
  FE/src/components/mypage/MyPageTab.tsx
Labels: frontend, fix

#167 [FE] 마이페이지 친구 데이터 타입 구분 기능 추가
  FE/src/components/mypage/details/friend/Follower.tsx
  FE/src/components/mypage/details/friend/Following.tsx
  FE/src/components/mypage/details/friend/MyFriend.tsx
  FE/src/components/mypage/details/friend/Search.tsx
  FE/src/pages/MyPage.tsx
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/data/FriendData.ts
  FE/src/util/friend.interface.ts
Labels: frontend, feature

#166 [BE] 팔로잉 삭제 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/DeleteFollowingRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
Labels: backend, feature, test

#170 [BE] 친구신청 수락/거절 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/ReceiveFollowRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java
Labels: backend, feature, test, refactor

#174 [BE] 이메일 인증 API 작성
  BE/build.gradle
  BE/src/main/java/com/newsainturtle/shadowmate/auth/entity/EmailAuthentication.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/RedisConfig.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
Labels: backend, feature, test

#172 [FE] 월별 페이지 컴포넌트 생성 및 배치
  FE/src/App.scss
  FE/src/api/Api.ts
  FE/src/assets/PretendardVariable.woff2
  FE/src/components/common/Text/index.tsx
  FE/src/components/planner/month/Month.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/styles/planner/Month.module.scss
  FE/src/util/planner.interface.ts
Labels: frontend, design, feature

#180 [BE] Dockerfile 생성
  BE/Dockerfile
Labels: backend, feature

#182 [FE] webpack 빌드 파일 압축 package 추가 및 설정
  FE/config/webpack.config.js
  FE/config/webpack.prod.js
  FE/package-lock.json
  FE/package.json
  FE/src/styles/global.d.ts
Labels: frontend, setting

#177 [BE] 이메일 인증 응답 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/CheckEmailAuthenticationCodeRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/SendEmailAuthenticationCodeRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthControlloerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
Labels: backend, feature, test

#183 [BE] MailConfig 생성
  BE/src/main/java/com/newsainturtle/shadowmate/config/MailConfig.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java
Labels: backend, feature, refactor

#190 [FE] TypeScript 버전 다운그레이드 변경 (-> v 5.0.4)
  FE/config/webpack.prod.js
  FE/package-lock.json
  FE/package.json
Labels: frontend

#189 [BE] SonarQube 적용
  BE/build.gradle
Labels: backend, feature

#191 [FE] TypeScript 버전 변경 (-> v 4.9.5)
  FE/package-lock.json
  FE/package.json
Labels: frontend, setting

#193 [FE] TypeScript 버전 업그레이드 변경 (-> v 5.1.6)
  FE/package-lock.json
  FE/package.json
Labels: frontend, feature

#194 [BE] 소나큐브 코드 악취 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddTimeTableRequest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryColorRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/UserRepositoryTest.java
Labels: backend, refactor

#197 [BE] Sonarqube 버전 수정
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.properties
Labels: backend, refactor

#198 [BE] 소나큐브 코드 악취 수정
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
Labels: backend, test, refactor

#188 [FE] 일일 플래너 타임테이블 컴포넌트 생성 및 배치
  FE/src/components/planner/day/CustomCursor.tsx
  FE/src/components/planner/day/TimeTable.tsx
  FE/src/components/planner/day/TodoItem.tsx
  FE/src/components/planner/day/TodoItemChoice.tsx
  FE/src/components/planner/day/TodoList.tsx
  FE/src/hooks/configStore.ts
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/planner/daySlice.ts
  FE/src/styles/planner/day.module.scss
  FE/src/util/data/DayTodos.ts
Labels: frontend, design, feature

#207 [BE] cors에러 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/CorsConfig.java
Labels: backend, fix

#209 [BE] 소나큐브 코드 악취 수정
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryColorRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
Labels: backend, fix, refactor

#210 [BE] 구글 로그인 API 작성
  BE/build.gradle
  BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/SecurityConfig.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetails.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtProvider.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/PrincipalOauth2UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
Labels: backend, feature, refactor

#208 [FE] 일별 플래너 Redux로 상태 관리 및 타임 테이블 기능 수정
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/item/MyPageCategoryItem.tsx
  FE/src/components/planner/day/CustomCursor.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/TimeTable.tsx
  FE/src/components/planner/day/TodoList.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoItemChoice.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/planner/daySlice.ts
  FE/src/styles/planner/day.module.scss
  FE/src/util/data/CategoryData.ts
  FE/src/util/data/DayTodos.ts
  FE/src/util/planner.interface.ts
Labels: frontend, design, feature

#215 [BE] 로그인 응답 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetails.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java
Labels: backend, feature, refactor

#214 [BE] 주간 플래너 조회 메소드 생성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
Labels: backend, feature, test

#204 [BE] 회원탈퇴 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/exception/UserErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, feature, test

#216 [FE] BaseUrl 및 Axios 메서드 설정
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
Labels: frontend, feature

#218 [BE] 이메일 인증 로직 수정
  BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java
Labels: backend, feature, test

#220 [BE] 테스트코드 리팩토링
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/UserRepositoryTest.java
Labels: backend, test, refactor

#202 [BE] 프로필 사진 수정 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UpdateProfileImageRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, feature, test, refactor

#229 [BE] 구글 계정에서 네이버 계정으로 변경
  BE/src/main/java/com/newsainturtle/shadowmate/config/MailConfig.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java
Labels: backend, feature, fix

#227 [BE] 로그인 유저ID 값 응답 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetails.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetailsService.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
Labels: backend, refactor

#224 [BE] 중복이메일 확인 레포지토리 메소드 수정
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java
Labels: backend, feature, test

#230 [BE] 구글 로그인 API 수정
  BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java
Labels: backend, refactor

#232 [BE] corsconfig 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/CorsConfig.java
Labels: backend, refactor

#241 [BE] 로그인시 email 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetails.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetailsService.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java
Labels: backend, fix

#234 [BE] RedisConfig 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/RedisConfig.java
Labels: backend, refactor

#238 [BE] 구글 로그인 ID 반환 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/PrincipalOauth2UserService.java
Labels: backend, feature, refactor

#244 [FE] BaseUrl.ts 변수 중괄호 제거
  FE/src/api/BaseUrl.ts
Labels: frontend, refactor

#236 [FE] 로그인 API 연결
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/api/JsonAxios.ts
  FE/src/components/auth/login/Login.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/hooks/configStore.ts
  FE/src/index.tsx
  FE/src/store/authSlice.ts
  FE/src/store/planner/weekSlice.ts
  FE/src/styles/auth/Login.module.scss
  FE/src/util/PrivateRoute.tsx
Labels: frontend, feature

#245 [FE] 회원가입 API 연결
  FE/src/api/Api.ts
  FE/src/components/auth/signup/Signup.tsx
  FE/src/components/common/Button/index.tsx
  FE/src/styles/auth/Signup.module.scss
  FE/src/styles/common/Button.module.scss
  FE/src/util/regex.ts
Labels: frontend, design, feature

#249 [FE] 주간 플래너 API 연결
  FE/src/api/Api.ts
  FE/src/api/JsonAxios.ts
  FE/src/components/planner/week/Week.tsx
  FE/src/components/planner/week/WeekTodo.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/components/planner/week/list/WeekItemInput.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/components/planner/week/todo/WeekTodo.tsx
  FE/src/components/planner/week/todo/WeekTodoInput.tsx
  FE/src/components/planner/week/todo/WeekTodoItem.tsx
  FE/src/pages/Planner/WeekPage.tsx
  FE/src/store/authSlice.ts
  FE/src/store/planner/weekSlice.ts
  FE/src/store/weekSlice.ts
  FE/src/util/data/WeekTodos.ts
  FE/src/util/getThisWeek.ts
Labels: frontend, feature

#253 [BE] 구글 로그인 API 주소 수정
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java
Labels: backend, refactor

#254 [BE] 플래너 공개 여부 설정 로직 수정
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/FollowRequestRepositoryTest.java
Labels: backend, feature, test

#251 [FE] 일별 플래너 일부 기능 추가 수정
  FE/src/components/planner/day/CustomCursor.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoItemChoice.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/planner/daySlice.ts
  FE/src/store/planner/weekSlice.ts
  FE/src/util/data/DayTodos.ts
  FE/src/util/planner.interface.ts
Labels: frontend, feature, fix

#256 [FE] 웹팩 svg 설정 수정
  FE/config/webpack.config.js
Labels: frontend, setting

#242 [FE] 구글 로그인 API 연결
  FE/src/components/auth/login/Login.tsx
  FE/src/store/authSlice.ts
Labels: frontend, feature

#255 [FE] favicon 및 사이트명 변경
  FE/config/webpack.config.js
  FE/public/favicon.svg
  FE/public/index.html
Labels: frontend, design, feature

#259 [FE] 구글 로그인 후 쿠키 삭제
  FE/src/api/MultipartAxios.ts
  FE/src/components/auth/login/Login.tsx
  FE/src/store/authSlice.ts
Labels: frontend, feature

#261 [FE] BaseURL 수정 및 userId 분리
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/components/planner/week/Week.tsx
  FE/src/components/planner/week/todo/WeekTodoInput.tsx
  FE/src/components/planner/week/todo/WeekTodoItem.tsx
  FE/src/store/authSlice.ts
Labels: frontend, refactor

#263 [BE] Social Entity 추가
  BE/src/main/java/com/newsainturtle/shadowmate/social/entity/Social.java
Labels: backend, feature

#265 [BE] 소셜 공유 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/ShareSocialRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java
Labels: backend, feature, test

#257 [BE] 소나큐브 코드 악취 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/SetAccessScopeRequest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryColorRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/FollowRequestRepositoryTest.java
Labels: backend, refactor

#267 [BE] 플래너 공개 여부 설정 로직 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/SocialRepositoryTest.java
Labels: backend, feature, test

#269 [FE] dockerfile 수정
  FE/Dockerfile
Labels: frontend, refactor

#272 [BE] 플래너 조회 코드 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
Labels: backend, feature, test, refactor

#273 [FE] 마이페이지 카테고리 설정 API 연결
  FE/src/components/mypage/MyPageDetail.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/item/CategoryColorItem.tsx
  FE/src/components/mypage/item/CategoryColorList.tsx
  FE/src/components/mypage/item/MyPageCategoryItem.tsx
  FE/src/components/mypage/list/CategoryList.tsx
  FE/src/hooks/configStore.ts
  FE/src/pages/MyPage.tsx
  FE/src/store/mypageSlice.ts
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/planner.interface.ts
Labels: frontend, feature

#275 [FE] 월별 플래너 조회 API 연결
  FE/src/api/Api.ts
  FE/src/components/planner/month/Month.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/hooks/configStore.ts
  FE/src/store/planner/monthSlice.ts
Labels: frontend, feature
