Repository NewSainTurtle/ShadowMate, pull requests merged in 2023-12, with the labels that each got.

#480 [FE] 캘린더 팔로우 수 에러 수정
  FE/src/components/planner/month/Month.tsx
Labels: frontend, fix

#502 [BE] 팔로우 카운트 수 API 수정
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
Labels: backend, fix

#508 [BE] 스프링부트 타임존 설정
  BE/src/main/java/com/newsainturtle/shadowmate/ShadowmateApplication.java
Labels: backend, fix

#509 [FE] 일별 플래너에서 공유 취소 및 삭제 API 연결
  FE/src/components/planner/day/Header.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/planner/daySlice.ts
Labels: frontend, feature, fix

#514 [FE] 비밀번호, 비밀번호 확인 일치 해결
  FE/src/components/auth/signup/Signup.tsx
  FE/src/components/mypage/details/myInfo/MyPassword.tsx
Labels: frontend, feature, fix

#515 [FE] 회원가입 약관동의 만들기
  FE/src/components/auth/signup/Signup.tsx
  FE/src/components/auth/signup/SignupAccount.tsx
  FE/src/components/auth/signup/SignupContract.tsx
  FE/src/components/common/Checkbox/index.tsx
  FE/src/styles/auth/Signup.module.scss
  FE/src/styles/common/Checkbox.module.scss
  FE/src/util/Consent.ts
Labels: frontend, design, feature

#510 [FE] 소셜페이지 높이 수정
  FE/src/styles/social/Social.module.scss
Labels: frontend, design, refactor

#476 [FE] 타임테이블 할 일 없을 때 helper text hover할 때만 보이기
  FE/src/components/common/Checkbox/index.tsx
  FE/src/components/planner/day/CustomCursor.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/planner/daySlice.ts
  FE/src/styles/planner/day.module.scss
Labels: frontend, design, fix

#520 [BE] Date타입에서 LocalDate타입으로 변경
  BE/src/main/java/com/newsainturtle/shadowmate/common/DateCommonService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Weekly.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/DdayRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/dto/SearchSocialResponse.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
Labels: backend, fix

#517 [FE] 캘린더 프로필 팔로잉 신청 버튼 생성 및 API 연결
  FE/src/components/common/FriendProfileIcon/index.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/store/friendSlice.ts
  FE/src/styles/common/Profile.module.scss
Labels: frontend, feature

#521 [FE] 캘린더 소개글 여백 추가 및 높이 수정
  FE/src/styles/planner/Month.module.scss
Labels: frontend, design, feature

#523 [FE] 캘린더 방명록 작성자의 월별 캘린더로 이동 및 방명록 엔터키 사용하여 등록
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
  FE/src/styles/planner/Month.module.scss
  FE/src/util/data/GuestBookData.ts
  FE/src/util/planner.interface.ts
Labels: frontend, feature

#525 [BE] 엔티티 LocalDate타입에서 String타입으로 변경
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Weekly.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/DdayRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/dto/SearchSocialResponse.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
Labels: backend, fix

#530 [FE] 마이페이지 프로필 삭제 시 모달 에러 수정
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
Labels: feature, fix

#535 [BE] 회원가입 후 레디스에서 이메일 인증 데이터 삭제
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java
Labels: backend, fix

#534 [BE] 소셜회원가입, 일반 가입 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java
Labels: backend, refactor

#541 [BE] 이메일 중복허용에 의한 findEmail 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtProvider.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
Labels: backend, test, refactor

#531 [FE] 사용자 서비스 설문 컴포넌트 생성
  FE/src/components/auth/login/Login.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/Popup/index.tsx
  FE/src/components/planner/month/Month.tsx
  FE/src/store/modalSlice.ts
  FE/src/styles/common/Header.module.scss
  FE/src/styles/common/Popup.module.scss
Labels: frontend, design, feature

#536 [FE] 카테고리 생성 시 기본 색상 설정 및 이모지 안내 문구 변경
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/item/CategoryColorItem.tsx
  FE/src/components/mypage/item/CategoryColorList.tsx
  FE/src/styles/mypage/MyPage.module.scss
Labels: frontend, design, feature

#539 [FE] 다른 사람의 주별 플래너에서 회고 입력 안내문 숨김 처리
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/styles/planner/Week.module.scss
Labels: frontend, feature

#518 [FE] 회원가입 에러 표시 해결
  FE/src/components/auth/signup/SignupAccount.tsx
  FE/src/components/auth/signup/SignupContract.tsx
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/mypage/details/myInfo/MyPassword.tsx
  FE/src/util/Consent.ts
Labels: frontend, design, feature, fix

#544 [FE] 일별 플래너 디데이 내용 표시 및 추가 디자인 설정
  FE/src/components/common/Popup/index.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/Ment.tsx
  FE/src/components/planner/month/Month.tsx
  FE/src/index.scss
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/planner/daySlice.ts
  FE/src/styles/planner/day.module.scss
Labels: frontend, design, feature

#548 [공통] 화면 이미지 추가
  README.md
Labels: docs

#547 [FE] 캘린더 방명록 닉네임 마우스 상태 변경
  FE/src/styles/planner/Month.module.scss
Labels: frontend, design, feature

#554 [FE] 메타데이터 이미지 링크 변경
  FE/public/index.html
Labels: frontend, design, feature

#557 [BE] 타임테이블 시간 유효성 검사 정규식 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddTimeTableRequest.java
Labels: backend, fix
