Repository NewSainTurtle/ShadowMate, pull requests merged in 2024-01, with the labels that each got.

#564 [BE] 플래너 글자 수 조정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateRetrospectionRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateTomorrowGoalRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/VisitorBook.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/WeeklyTodo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/AddCategoryRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/AddDdayRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/UpdateCategoryRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/UpdateDdayRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Category.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
Labels: backend, refactor

#561 [FE] 카테고리, 디데이 저장 안되는 에러 수정
  FE/src/components/mypage/MyPageFrame.tsx
Labels: frontend, fix

#566 [FE] 주별 플래너 Safari 에러 수정
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/styles/planner/Week.module.scss
Labels: frontend, fix

#569 [BE] 소셜 기간 필터 설정 및 소셜 조회 API 합치기
  BE/build.gradle
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/constant/SocialConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/controller/SocialController.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/dto/SearchSocialPlannerResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/entity/Social.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/exception/SocialErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialService.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialServiceTest.java
Labels: backend, feature, test, refactor

#567 [FE] 랜딩페이지 이미지 최적화
  FE/config/webpack.config.js
  FE/package-lock.json
  FE/package.json
  FE/src/assets/Imgs/landing_background.webp
  FE/src/pages/LandingPage.tsx
  FE/src/styles/auth/Landing.module.scss
  FE/src/styles/global.d.ts
Labels: frontend, refactor, setting

#575 [FE] 소나큐브 코드 악취 수정
  FE/src/components/auth/login/Login.tsx
  FE/src/components/common/Avatar/index.tsx
  FE/src/components/common/CategorySelector/index.tsx
  FE/src/components/common/Dday/index.tsx
  FE/src/components/common/Header/Menu.tsx
  FE/src/components/common/Modal/TokenExpiration.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/MyPageTab.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/mypage/details/friend/MyFriend.tsx
  FE/src/components/mypage/item/CategoryColorList.tsx
  FE/src/components/mypage/item/MyPageDdayItem.tsx
  FE/src/components/mypage/list/DdayList.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
  FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/components/planner/week/todo/WeekTodoItem.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/store/modalSlice.ts
  FE/src/util/PrivateRoute.tsx
  FE/src/util/TodoModule.ts
Labels: frontend, refactor

#574 [BE] 할일 진행중 상태 추가
  BE/src/main/java/com/newsainturtle/shadowmate/planner/enums/TodoStatus.java
Labels: backend, feature

#577 [BE] 타임테이블 중복 등록 가능하도록 로직 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/RemoveTimeTableRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/AddTimeTableResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/DailyPlannerTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/TimeTable.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TimeTableRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
Labels: backend, feature, test

#578 [FE] 소나큐브 코드 악취 수정 & 더미데이터 파일 제거
  FE/src/App.tsx
  FE/src/api/firebaseConfig.ts
  FE/src/components/auth/signup/SignupAccount.tsx
  FE/src/components/auth/signup/SignupContract.tsx
  FE/src/components/common/Dday/index.tsx
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/details/friend/MyFriend.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/mypage/item/MyPageDdayItem.tsx
  FE/src/components/planner/day/CustomCursor.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/Ment.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoItemChoice.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/components/social/SocialHeader.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/authSlice.ts
  FE/src/store/friendSlice.ts
  FE/src/store/planner/daySlice.ts
  FE/src/util/data/CategoryData.ts
  FE/src/util/data/DayTodos.ts
  FE/src/util/data/DdayData.ts
  FE/src/util/data/FriendData.ts
  FE/src/util/data/MyInfoData.ts
  FE/src/util/data/SocialData.ts
  FE/src/util/friend.interface.ts
  FE/src/util/resizeImage.ts
Labels: frontend, refactor

#587 [BE] 할일 순서 인덱스 생성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/AddDailyTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/DailyPlannerTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/TodoIndexResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/WeeklyPlannerDailyTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
Labels: backend, feature, test

#591 [FE] 할 일 상태 세모 표시 추가
  FE/src/api/Api.ts
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoItemChoice.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/util/planner.interface.ts
Labels: frontend, feature, refactor

#588 [FE] 카테고리, 디데이 최소 글자수 변경
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
Labels: frontend, refactor

#592 [FE] 주별 플래너 깜빡임 수정
  FE/src/components/planner/week/Week.tsx
Labels: frontend, refactor

#595 [BE] 할일 순서 변경 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/ChangeDailyTodoSequenceRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/AddDailyTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/DailyPlannerTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/WeeklyPlannerDailyTodoResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
Labels: backend, feature, test

#594 [FE] 캘린더 스크롤 생성
  FE/src/styles/planner/Month.module.scss
Labels: frontend, refactor

#590 [FE] 설정 버튼 생성
  FE/src/components/common/Header/Menu.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/Profile/index.tsx
Labels: frontend, refactor

#585 [FE] 캘린더 그래프 표시
  FE/src/components/planner/month/Month.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/components/planner/month/MonthGraph.tsx
  FE/src/styles/planner/Month.module.scss
  FE/src/util/colors.ts
Labels: frontend, refactor

#601 [BE] 타임테이블 삭제 로직 수정
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
Labels: backend, fix

#599 [BE] JWT Refresh Token 발급
  BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/ChangeTokenRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtProvider.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
Labels: backend, feature, test, refactor

#605 [BE] 자동로그인
  BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/RemoveTokenRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/SecurityConfig.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
Labels: backend, feature, test

#608 [FE] 토큰 재발급 로직 추가
  FE/src/App.tsx
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/api/JsonAxios.ts
  FE/src/components/auth/login/Login.tsx
  FE/src/store/authSlice.ts
Labels: frontend, feature, refactor

#610 [BE] 루틴 생성 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/AddRoutineRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/response/AddRoutineResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Routine.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/RoutineDay.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/RoutineTodo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/exception/PlannerSettingErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineDayRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineTodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineDayRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineTodoRepositoryTest.java
Labels: backend, feature, test

#611 [BE] 루틴 조회 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/response/GetRoutineListResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/response/GetRoutineResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineDayRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineDayRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineRepositoryTest.java
Labels: backend, feature, test

#616 [BE] 플래너 조회 시 루틴을 할일로 등록
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/RoutineTodo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineTodoRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineTodoRepositoryTest.java
Labels: backend, feature, test

#617 [BE] 캘린더 조회 시 루틴 카운트
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineTodoRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineTodoRepositoryTest.java
Labels: backend, feature, test

#623 [BE] 루틴 목록 조회 시 응답값에 카테고리 추가
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/response/GetRoutineResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
Labels: backend, refactor

#629 [BE] 카테고리 삭제 시 루틴 확인
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineRepositoryTest.java
Labels: backend, feature, test

#630 [BE] 할일 삭제 시 관련된 루틴할일 데이터 삭제
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineTodoRepository.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineTodoRepositoryTest.java
Labels: backend, feature, test

#624 [FE] 루틴 컴포넌트 생성
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/MyPageTab.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Routine.tsx
  FE/src/components/mypage/item/CategoryItem.tsx
  FE/src/components/mypage/item/DdayItem.tsx
  FE/src/components/mypage/item/RoutineItem.tsx
  FE/src/components/mypage/list/CategoryList.tsx
  FE/src/components/mypage/list/DdayList.tsx
  FE/src/components/mypage/list/RoutineList.tsx
  FE/src/hooks/configStore.ts
  FE/src/pages/MyPage.tsx
  FE/src/store/mypage/routineSlice.ts
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/planner.interface.ts
Labels: frontend, design, feature

#625 [FE] 소셜 기간 검색
  FE/config/webpack.config.js
  FE/package-lock.json
  FE/package.json
  FE/src/api/Api.ts
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/social/CardList.tsx
  FE/src/components/social/SocialHeader.tsx
  FE/src/components/social/SocialInput.tsx
  FE/src/hooks/configStore.ts
  FE/src/pages/SocialPage.tsx
  FE/src/store/socialSlice.ts
  FE/src/styles/common/DataRangePicker.css
  FE/src/styles/common/Input.module.scss
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/styles/social/Social.module.scss
Labels: frontend, design, feature, refactor

#618 [FE] 자동로그인 API 연결
  FE/src/App.tsx
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/api/JsonAxios.ts
  FE/src/components/auth/login/Login.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/hooks/configStore.ts
  FE/src/store/authSlice.ts
Labels: frontend, feature

#632 [FE] 루틴 조회 API 연결
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/components/mypage/details/diary/Routine.tsx
  FE/src/components/mypage/item/RoutineItem.tsx
  FE/src/components/mypage/list/RoutineList.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/store/mypage/routineSlice.ts
  FE/src/util/planner.interface.ts
Labels: frontend, feature

#633 [FE] 로그아웃 API 연결
  FE/src/App.tsx
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/api/JsonAxios.ts
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/details/myInfo/CancelMembership.tsx
  FE/src/store/authSlice.ts
Labels: frontend, feature

#639 [BE] 루틴 수정 API 작성
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/UpdateRoutineRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Routine.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineTodoRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineTodoRepositoryTest.java
Labels: backend, feature, test

#642 [BE] 회원탈퇴 시 로직 수정
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, test, refactor

#641 [FE] 자동로그인 및 토큰 갱신 에러 수정
  FE/src/App.tsx
  FE/src/api/Api.ts
  FE/src/api/JsonAxios.ts
Labels: frontend, fix

#643 [FE] 루틴 등록 API 연결
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/components/mypage/MyPageDetail.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/MyPageList.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/mypage/details/diary/Routine.tsx
  FE/src/components/mypage/item/RoutineItem.tsx
  FE/src/components/mypage/list/RoutineList.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/store/mypage/categorySlice.ts
  FE/src/store/mypage/ddaySlice.ts
  FE/src/store/mypage/routineSlice.ts
  FE/src/styles/common/DataRangePicker.css
  FE/src/styles/mypage/MyPage.module.scss
  FE/src/util/planner.interface.ts
Labels: frontend, feature

#646 [FE] 루틴 수정 및 삭제 모달 컴포넌트 생성
  FE/src/components/common/Modal/RoutineUpdateModal.tsx
  FE/src/components/mypage/MyPageFrame.tsx
Labels: frontend, design, feature

#650 [BE] 코드스멜 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/common/constant/CommonConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/constant/ConfigConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtExceptionHandler.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtProvider.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddDailyLikeRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddDailyTodoRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddTimeTableRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddWeeklyTodoRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/ChangeDailyTodoSequenceRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/RemoveDailyLikeRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/RemoveDailyTodoRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/RemoveTimeTableRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/RemoveWeeklyTodoRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/ShareSocialRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateDailyTodoRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateRetrospectionImageRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateRetrospectionRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateTodayGoalRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateTomorrowGoalRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateWeeklyTodoContentRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateWeeklyTodoStatusRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/AddDdayRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/AddRoutineRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/UpdateCategoryRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/UpdateDdayRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/constant/SocialConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
Labels: backend, refactor

#654 [BE] 팔로우 엔티티 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/Follow.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/FollowRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/FollowRequestRepositoryTest.java
Labels: backend, refactor

#644 [FE] 할일 드래그 이동 로직 추가 및 일별 플래너 적용
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoItemChoice.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/styles/planner/day.module.scss
  FE/src/util/DragModule.ts
Labels: frontend, design, feature, refactor

#657 [BE] 코드스멜 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerLikeRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
Labels: backend, test, refactor

#656 [FE] 할 일 순서 이동 제한 설정
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/util/DragModule.ts
Labels: frontend, feature, refactor

#658 [FE] 마이페이지 루틴 설정 로직 리팩토링
  FE/src/components/common/CategorySelector/index.tsx
  FE/src/components/common/Modal/mypage/NewItemContainer.tsx
  FE/src/components/mypage/MyPageDetail.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/MyPageList.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/mypage/details/diary/Routine.tsx
  FE/src/components/mypage/item/RoutineItem.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/store/mypage/categorySlice.ts
  FE/src/store/mypage/ddaySlice.ts
  FE/src/store/mypage/routineSlice.ts
  FE/src/styles/common/Modal.module.scss
  FE/src/styles/mypage/MyPage.module.scss
Labels: frontend, feature

#662 [FE] 새로고침 시 캘린더로 이동하는 에러 수정
  FE/src/App.tsx
Labels: frontend, fix

#665 [BE] 회원탈퇴 관련 로직 수정
  BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetailsService.java
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/PrincipalOauth2UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/VisitorBookRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/VisitorBookRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialServiceTest.java
Labels: backend, feature, test

#672 [BE] 엔티티 제약조건 변경
  BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/Follow.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/FollowRequest.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlannerLike.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/TimeTable.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/VisitorBook.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Weekly.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/WeeklyTodo.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Category.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/RoutineTodo.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/entity/Social.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/SocialRepositoryTest.java
Labels: backend, test, refactor

#673 [BE] 코드스멜 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/PrincipalOauth2UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
Labels: backend, refactor

#664 [FE] 설문 팝업 감추기 & 헤더 문의 버튼으로 변경
  FE/src/components/auth/login/Login.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/styles/common/DataRangePicker.css
Labels: frontend, feature, refactor

#667 [FE] 일별 플래너 리팩토링
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/util/TodoModule.ts
Labels: frontend, feature, refactor

#668 [FE] 주별 플래너 할 일 순서 변경
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/components/planner/week/list/WeekItemInput.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/components/planner/week/todo/WeekTodo.tsx
  FE/src/styles/planner/Week.module.scss
Labels: frontend, feature

#670 [FE] 로그인 시 엔터 동작 추가
  FE/src/components/auth/login/Login.tsx
Labels: frontend, feature

#674 [FE] 마이페이지 변경사항 반영
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/mypage/details/diary/Routine.tsx
  FE/src/styles/mypage/MyPage.module.scss
Labels: frontend, feature

#679 [FE] 주별 플래너 글자수 에러 수정
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/components/planner/week/list/WeekItemInput.tsx
  FE/src/components/planner/week/todo/WeekTodoInput.tsx
  FE/src/components/planner/week/todo/WeekTodoItem.tsx
Labels: frontend, fix

#680 [FE] 입력 글자수 제한 적용
  FE/src/components/auth/login/Login.tsx
  FE/src/components/auth/signup/SignupAccount.tsx
  FE/src/components/common/Input/index.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/mypage/details/diary/Routine.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/mypage/details/myInfo/MyPassword.tsx
  FE/src/components/social/SocialInput.tsx
Labels: frontend, feature, refactor

#683 [FE] 마이페이지 카테고리/디데이/루틴 삭제 에러 수정 및 디데이 min-height 설정
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Dday.tsx
  FE/src/components/mypage/details/diary/Routine.tsx
  FE/src/styles/mypage/MyPage.module.scss
Labels: frontend, fix

#682 [공통] 버전2 업데이트 내용 리드미에 추가
  README.md
Labels: docs
