Repository NewSainTurtle/ShadowMate, pull requests merged in 2024-03, with the labels that each got.

#716 [FE] 회원가입 테스트 코드 작성
  FE/cypress.config.ts
  FE/cypress/e2e/signup.cy.ts
  FE/src/components/auth/signup/Signup.tsx
  FE/src/components/auth/signup/SignupAccount.tsx
  FE/src/components/auth/signup/SignupContract.tsx
Labels: frontend, test, refactor

#718 [FE] jest 삭제 및 폴더 구조 변경
  FE/.eslintrc
  FE/cypress.config.ts
  FE/cypress/e2e/auth/login.cy.ts
  FE/cypress/support/commands.ts
  FE/cypress/support/e2e.ts
  FE/cypress/tsconfig.json
  FE/jest.config.ts
  FE/package-lock.json
  FE/package.json
  FE/src/__tests__/__snapshots__/mainpage.test.tsx.snap
  FE/src/__tests__/mainpage.test.tsx
  FE/tsconfig.jest.json
  FE/tsconfig.json
Labels: frontend, refactor

#719 [공통] 리드미 수정
  README.md
Labels: docs
