Repository NewSainTurtle/ShadowMate, pull requests merged in 2024-02, with the labels that each got.

#688 [BE] 코드스멜 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/PrincipalOauth2UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
Labels: backend, test, refactor

#689 [FE] 코드스멜 리팩토링
  FE/src/App.tsx
  FE/src/api/BaseUrl.ts
  FE/src/api/JsonAxios.ts
  FE/src/components/auth/login/Login.tsx
  FE/src/components/common/Button/index.tsx
  FE/src/components/common/Header/Menu.tsx
  FE/src/components/common/Text/index.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/MyPageTab.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/diary/Routine.tsx
  FE/src/components/mypage/item/DdayItem.tsx
  FE/src/components/mypage/item/RoutineItem.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
  FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx
  FE/src/components/planner/month/MonthDetailInfo/Statistics.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/components/planner/month/MonthGraph.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/index.scss
  FE/src/pages/commonPage.tsx
  FE/src/store/mypage/routineSlice.ts
  FE/src/styles/common/Input.module.scss
  FE/src/util/getThisWeek.ts
Labels: frontend, refactor

#690 [FE] 소나큐브 코드 악취 리팩토링
  FE/.eslintrc
  FE/package-lock.json
  FE/package.json
  FE/src/components/auth/signup/SignupAccount.tsx
  FE/src/components/common/Dday/index.tsx
  FE/src/components/common/Input/index.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/details/diary/Category.tsx
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/mypage/item/DdayItem.tsx
  FE/src/components/mypage/item/RoutineItem.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/day/todo/TodoItemChoice.tsx
  FE/src/components/planner/day/todo/TodoList.tsx
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/components/planner/week/todo/WeekTodoItem.tsx
  FE/src/components/social/CardList.tsx
  FE/src/components/social/SocialHeader.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/store/planner/daySlice.ts
  FE/src/store/planner/monthSlice.ts
  FE/src/styles/planner/day.module.scss
  FE/src/styles/social/Social.module.scss
  FE/src/util/DragModule.ts
  FE/src/util/TodoModule.ts
  FE/src/util/getThisWeek.ts
  FE/src/util/planner.interface.ts
Labels: frontend, refactor, setting

#693 [FE] eslint 리팩토링
  FE/.eslintrc
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/api/JsonAxios.ts
  FE/src/components/auth/signup/SignupAccount.tsx
  FE/src/components/common/Dday/index.tsx
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/common/FriendProfileIcon/index.tsx
  FE/src/components/common/Popup/index.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/details/friend/MyFriend.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
  FE/src/components/mypage/details/myInfo/CancelMembership.tsx
  FE/src/components/mypage/details/myInfo/MyInfo.tsx
  FE/src/components/mypage/details/myInfo/MyPassword.tsx
  FE/src/components/planner/day/Header.tsx
  FE/src/components/planner/day/todo/TimeTable.tsx
  FE/src/components/planner/day/todo/TodoItem.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/components/social/CardItem.tsx
  FE/src/components/social/CardList.tsx
  FE/src/hooks/configStore.ts
  FE/src/pages/Planner/DayPage.tsx
  FE/src/store/alertSlice.ts
  FE/src/store/authSlice.ts
  FE/src/store/friendSlice.ts
  FE/src/store/modalSlice.ts
  FE/src/store/planner/daySlice.ts
  FE/src/util/DragModule.ts
  FE/src/util/EventControlModule.tsx
  FE/src/util/auth.interface.ts
  FE/src/util/friend.interface.ts
  FE/src/util/planner.interface.ts
Labels: frontend, refactor

#698 [BE] 팔로우와 유저 서비스 간 의존성 제거
  BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/response/SearchUserResponse.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/UserFollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/UserFollowServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/UserFollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
Labels: backend, refactor

#699 [BE] 소셜과 유저, 플래너 서비스 간 의존성 제거
  BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/controller/SocialController.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/exception/SocialErrorResult.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialService.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/UserPlannerSocialService.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/UserPlannerSocialServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/social/UserPlannerSocialServiceTest.java
Labels: backend, refactor

#700 [BE] 플래너 설정과 다른 서비스 간 의존성 제거
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java
  BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerRoutineService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerRoutineServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/RoutineService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/RoutineServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/UserPlannerSettingService.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/UserPlannerSettingServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialService.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/UserPlannerSocialServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java
  BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerAccessScopeServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerRoutineServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/RoutineServiceTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialServiceTest.java
Labels: backend, refactor

#697 [FE] eslint 리팩토링
  FE/src/App.tsx
  FE/src/api/Api.ts
  FE/src/api/JsonAxios.ts
  FE/src/components/auth/login/Login.tsx
  FE/src/components/common/Alert/index.tsx
  FE/src/components/common/CategorySelector/index.tsx
  FE/src/components/common/Header/Menu.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/MyPageFrame.tsx
  FE/src/components/mypage/details/diary/Diary.tsx
  FE/src/components/planner/month/Month.tsx
  FE/src/components/planner/month/MonthCalendar.tsx
  FE/src/components/planner/month/MonthDetail.tsx
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
  FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx
  FE/src/components/planner/month/MonthDetailInfo/Statistics.tsx
  FE/src/components/planner/month/MonthFriends.tsx
  FE/src/components/planner/week/Week.tsx
  FE/src/components/planner/week/list/WeekItem.tsx
  FE/src/components/planner/week/list/WeekItemInput.tsx
  FE/src/components/planner/week/list/WeekList.tsx
  FE/src/components/planner/week/todo/WeekTodoInput.tsx
  FE/src/components/planner/week/todo/WeekTodoItem.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/Planner/MonthPage.tsx
  FE/src/store/mypage/routineSlice.ts
  FE/src/store/planner/weekSlice.ts
  FE/src/util/getThisWeek.ts
Labels: frontend, refactor

#705 [FE] 로그인 테스트 코드 작성
  FE/cypress/e2e/login.cy.ts
  FE/src/App.tsx
  FE/src/components/auth/login/Login.tsx
  FE/src/components/common/Input/index.tsx
  FE/src/styles/auth/Login.module.scss
Labels: frontend, fix, test

#712 [BE] 람다를 활용한 서비스 코드 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
  BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
Labels: backend, refactor

#707 [FE] API 리팩토링
  FE/src/App.tsx
  FE/src/api/Api.ts
  FE/src/api/BaseUrl.ts
  FE/src/components/common/FriendProfile/index.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
  FE/src/components/planner/month/Month.tsx
  FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx
Labels: frontend, refactor

#714 [BE] 코드스멜 리팩토링
  BE/src/main/java/com/newsainturtle/shadowmate/planner/service/UserPlannerServiceImpl.java
  BE/src/test/java/com/newsainturtle/shadowmate/auth/AuthControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/auth/repository/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/follow/FollowControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/follow/repository/FollowRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/social/SocialControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/social/repository/SocialRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/user/UserControllerTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/user/repository/UserRepositoryTest.java
  BE/src/test/java/com/newsainturtle/shadowmate/user/service/UserServiceTest.java
Labels: backend, refactor

#710 [FE] 팔로우 목록 스크롤
  FE/src/components/mypage/details/friend/MyFriend.tsx
  FE/src/components/mypage/details/friend/MyFriendFrame.tsx
  FE/src/styles/mypage/MyPage.module.scss
Labels: frontend, design, fix
